{
  pkgs,
  config,
  ...
}: let
  lan = import ../../settings/networking/configuration.nix;
  inherit (lan.services.k3s) ip mac;
  inherit (lan) gateway;
in {
  imports = [
    ./hardware-configuration.nix
    ./networking.nix
  ];

  nixpkgs.config.allowUnfree = true;

  sops = {
    defaultSopsFile = ../../../secrets/nodes/gpu01/secrets.yaml;
    secrets.k3s-token = {
      path = "/etc/k3s/token";
      mode = "0600";
      owner = "root";
    };
  };

  #boot.kernelPackages = pkgs.linuxPackages_latest;

  services.xserver.videoDrivers = ["nvidia"];
  hardware.nvidia = {
    modesetting.enable = true;
    open = false; # use proprietary driver
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
  hardware.nvidia-container-toolkit = {
    enable = true;
    # Add nvidia-smi, nvidia-cuda-mps-*, nvidia-debugdump, nvidia-powerd,
    # nvidia-ctk to the CDI spec mounts. Silences the device plugin's
    # "Could not locate nvidia-smi" / etc. warnings during CDI spec
    # generation and makes the binaries available inside workload pods.
    mount-nvidia-executables = true;
  };
  #virtualisation.containerd.enable = true;

  # Put nvidia-container-runtime on k3s's service PATH so k3s's startup
  # `findNvidiaContainerRuntimes` (exec.LookPath) discovers it and registers
  # the `nvidia` runtime in the auto-generated containerd config. Pods setting
  # runtimeClassName: nvidia then route through nvidia-container-runtime, which
  # applies the CDI spec at /var/run/cdi/nvidia-container-toolkit.json — mounting
  # /dev/nvidia* and the /nix/store driver libs into the pod. Required for the
  # k8s-device-plugin / gpu-feature-discovery bootstrap pods to call NVML.Init
  # (kubelet doesn't propagate the cdi.k8s.io/* pod annotations to container CRI
  # annotations on k8s ≥1.28, so the runtime-class hook is how we get CDI
  # injection onto these pods).
  systemd.services.k3s.path = [
    config.hardware.nvidia-container-toolkit.package.tools
    # nvidia-container-runtime is a wrapper: it exec.LookPath's the low-level
    # OCI runtime (runc or crun) it'll delegate to. k3s ships its own runc
    # internally but doesn't put it on the system PATH, so without this the
    # runtime exits with `no runtime binary found from candidate list: [runc crun]`.
    pkgs.runc
  ];

  # Force nvidia-container-runtime to CDI mode. Default "auto" mode tries to
  # detect CDI annotations on the OCI spec and falls back to legacy injection
  # via nvidia-container-cli when none are present. Legacy mode would require
  # the libnvidia-container package (not pulled in by hardware.nvidia-container-toolkit
  # on NixOS), so without this the runtime errors out at container start. CDI
  # mode reads /var/run/cdi/nvidia-container-toolkit.json (generated by the
  # cdi-generator service that hardware.nvidia-container-toolkit.enable wires
  # up) and applies it directly — no nvidia-container-cli needed.
  environment.etc."nvidia-container-runtime/config.toml".text = ''
    [nvidia-container-runtime]
    mode = "cdi"
    log-level = "info"
  '';

  services.k3s = {
    enable = true;
    role = "agent";
    serverAddr = "https://${ip}:6443";
    tokenFile = config.sops.secrets.k3s-token.path;

    extraFlags = [
      # NFD/GFD apply the canonical nvidia.com/gpu.* labels; the taint stays
      # so non-GPU workloads can't land here.
      "--node-taint=nvidia.com/gpu=true:NoSchedule"
    ];
  };

  # ZFS Support
  #boot.supportedFilesystems = ["zfs"];
  #boot.zfs.forceImportRoot = false;

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Time
  time.timeZone = "Europe/Stockholm";

  # SSH
  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
  };

  # User
  users.users.admin = {
    isNormalUser = true;
    extraGroups = ["wheel"];
    openssh.authorizedKeys.keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEn6aDAJkpZfBKdrin86mgv97ZqAPg/5PlYRXPDe6B4W home"];
  };

  security.sudo.wheelNeedsPassword = false;

  environment.systemPackages = with pkgs; [vim git curl];

  system.stateVersion = "25.11";
  nix.settings = {
    experimental-features = ["nix-command" "flakes"];
    trusted-users = ["root" "@wheel"];
  };
}
