apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secrets
  namespace: rustfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: rustfs-secrets
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef: { key: rustfs-secrets, property: access_key }
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef: { key: rustfs-secrets, property: secret_key }
