apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: rustfs-svc
      port:
        number: 9000
  tls:
    - hosts:
        - rustfs
