---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-creds
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCSuwB7seebeXt0qvsv5Y3JKPzP2w2gLmgNYomJB4N2wLtRGHO2Ucwc+5qi8CsRPGqsP6XPt6qt5212+82lRtmhzwl1oEP7vTZzsR0287okJVu7LuDZuimV7/miuWuzJbsDnJtYcaIiK1xzP7K1LaEOk5W4UKSAUPdym27TdBKlgAmg+L7Zf/96Mv2xX6kQttXdvwRLoXkUfN41Bln+vPwlfm8xHGtzYtTbHEQfrxXksL1LlUatX5W8tXFMpTLFCWMoPsk5UaE/uinDMxbLfIBrrJMTyL0tSE7rnuB1I09/vJlDWiu2JKbNLEuvlrohm6Ex6vkaB0D+ulSk2rsL3HXBWdC3UvH8MWnNK9cVQ64BsKLpptSo6iWAn2w3WwWgpXZzgktoRJtnTeyG2L7ylTjFjVYlR2ETlwN4MY2F4waSZvuZjEi1FLtsKRPnppKsJxsb3XUGg6QLt9JW9IV0fnOzh8cz5O4V9NJz7BhoEZRNs7k9otWCNedE6k88AQ0Wb8/wlPZCip84RJ9jLPdPdLsYciQe60HJi2yOmmEK3KBUQe6rEw6lN39waKPGjywDIc77baNo/z3oRecTEF/aTO4mZ5S2E1bh5TZHRW63CHUPCYXnJposdMG2+CfuTkUwstxZKbiigyemkcgv/2j5kZY5fI4eNBxEIVh3JoYf+x9v3GJzsXqI3il5RnJWF0S2v+xEAkQ8V1Cf2f2r9tFnpYxJIhsavA==
    RUSTFS_SECRET_KEY: AgDjjZ5W0kACEFHkOkSB/wAT5AynkS7gBKusXhO+xyfPsa36efTPDlVCT8KU5f98NsF4Vm31i5FIwm5DZLSAw5MGHTE+3BymqkGR+GA/NuR92tkwmowA3mj8D06/21h7YjZcplQy6RVtN7+1qEoB3Exp4gktPxw9ehbIL/F/GjBBOReKnF53iYCSq5aPH29Jp2VIxfmJKEFMYl4hbpKLdJumMW62yIAEQwlVbVK1FQ6Ae5Ly/DioFcHkPMD/ZK2RkDu/hZ75gXS380OsmSw+8YgRa2yjmAIgvtxbovh+G0MxjgRF9yuD3xxTtCBmPn34y0m3DDSecnNiiArxUtkSLNpMZ4KvEsphiu7ZmDCSirqi6KJk9CGG6X1mPg1AHIHeQ0bIq87iwMxG9IOHfr90hI/bg0hRV1lOOqQLqE5X+S1Mcu4VXtpu/Smx9pKP7t1EnT8Wu//yuo0CMnkIbl70LP2P9oy4AadXS6AfHwm/HzEblCQhA1Ra/5XYluRlU9aQE/e9raLe7aqODmk13cHbNY/LbKY3k9rZn7B1ndlmIAqmFzdwZwihMlXQOaqb0YVp+CHIC251ocskGVArukASP3yNmjHYCrpEWxWeLHo5VE2KnQ8kY8bmF+Ck88gXZXQYnlh8s4wn38XcLqwiwcyzBB1KRdezsNOm5e8FroS4Xm3rTf2PCsTa4KeEgF7nrdd26l0sLUyrQ/LizbPc8V7HAuGGw+HFZbSUKFl50bqsfAmP+VJAYL42Us08
  template:
    metadata:
      name: rustfs-creds
      namespace: rustfs
