apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-external-secrets
  namespace: evidently
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: rustfs-secrets
  data:
    - secretKey: FSSPEC_S3_KEY
      remoteRef: { key: rustfs-secrets, property: access_key }
    - secretKey: FSSPEC_S3_SECRET
      remoteRef: { key: rustfs-secrets, property: secret_key }
---
#apiVersion: external-secrets.io/v1
#kind: ExternalSecret
#metadata:
#  name: tailscale-external-secrets
#  namespace: evidently
#spec:
#  refreshInterval: 1h
#  secretStoreRef:
#    name: in-cluster
#    kind: ClusterSecretStore
#  target:
#    name: tailscale-secrets
#    template:
#      data:
#        evidently_SERVER_ALLOWED_HOSTS: "evidently.{{ .TAILNET }},evidently.{{ .TAILNET }}:*,127.0.0.1:*,localhost:*"
#  data:
#    - secretKey: TAILNET
#      remoteRef: { key: tailscale-secrets, property: tailnet }
