---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: siralim-codex
spec:
  encryptedData:
    .dockerconfigjson: AgBLIWkKeC5XxbyvfAlUjNJPcdWIYv0q9dhBK8+v9xcld2bFJi0md5jFRiKDxHlT8o7D+D9jos4hldBwxTSGLuzLXASrHXlChJ+RRBpSf8zE28uF9ShNi+FJ8flR9L2mRyF6vIx9hzmXM8thCA0iouA9ajUxxjLQ68bk7mMiUFeks18qJwKl+wMJFaH/syeXiDfh91AWt0AWVtRBrHBsW+RZrN7kUWD8+NKH8qy9ETWh/1zajDnHqPZWmPYbq6VV7DrrlzpQYN+qttY/WvrqDDSHuspUo6qx94ZN2swrD9z4dwx3zVWop1VQ/0Y1V2n1+3hxPzv04vajrJnP80I8CCHlPmEA73EynP5CpVsXHiKlqLX0cfx+5hlE86Fm0/KKmfl2xddfNR7uWfyZOimG74JXRVpMWARCPgYu5xKFy567f9jzjXwTQmU9TdqhPSQj4rWcq+3J2ZvxTphkM0wp5n8ArdO7V0Ydtf2d6nrUls/xmC6WB+Gxoakmph+nnsmi616okWQ/ClsTRHdXnj8DmFU0a/o3sgcN3offOqA+nGCj2uKqLknpmRnKVaUCc+G37lyAYgrkSWmTABK+CKFaLCg7KMWmRMEgpkGJFEvtORI016GIEu5pg6EHk8vyrOEmp5Hn7lbmqaM8ZW1G7o5M2Yk8r6aAJEw7JscWPAYsDqXkUhuA3C45xvS6+mhfGWdJboL3VZyQwCMFI0L3vI2nQspYtkNzNqhUeuYYlojFXx1JYs5jo4ZOrD+xaLhm0+5i5arh8+J5uN3uPrZHhUMYWh23LRI1LKrEpToiW/qeCx4oA20alttraaWx6I0DBSMWGQyBsiTXQ0jvwSLltvz4eVeYq1ioP9eCyMTxqDlyse6UyTnMsO5Izosvs2zTwM3PhICWT+ugAW/rLeDXMfDmgP9D3lAB3ZmCOxV7h9+LMOku+phpTrHu9omb1BByhNWi1a8=
  template:
    metadata:
      name: ghcr-pull
      namespace: siralim-codex
    type: kubernetes.io/dockerconfigjson
