---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: teach
spec:
  encryptedData:
    .dockerconfigjson: AgDSQb30UTh/DbUaJZX7eeQgxywrMSQSKzZAsalRkp7fqT84qnUmyzNQvXfes+jsl9Y30EBxGzcaWrm6I8NXSk4VYdfQ6MFVFkI3h3nfu7KcBC3UpZa4ElzzQO/ZrlUv81auF/mc3YACaQXb2y52UG9P+XMgHRaTusHs1v7e7MkI0DOV3kIXD5GxXNXuY/khGOTTclrXkl66t5YPY3vSFLoli2e3RSClDZhINlA7HF6z2xy9+FRjLjgkRYuZIffMX47igAkCrmIILqOa3mrCr0DhZ2bLvFBLv7o63OtR4VlckefQjA/0V3B1MnpG7gXiuln358jyS6xR3td+yssS3GZ4OY3ZP9rgZKLrPC7trJjIIDMoQS4ZAdjhr4PWAFCOpZLc9rgnVcJM1ciqAF85l961nius9Klq2wDm7JD4y7AacB/MlN1gJgoLmjdXqMCF3/MVZluI2O5Dth8w7++woBaCU9oDx/z3WyoXBvtvmw2IYs8nWLwgaqOuJ840LVQ11sQc07GZZKuMAe338ofQ4nvn6w83IsBXdf/zKla/5uGDI3VOnVGl8vRI96LmRtlP81MSWlYSBxibnqTeV/oCdlsW4oYTlJMUosSH60gRk9+DdScjuIYkN1gNnD6Xy+p++PRw+0Oq4ClaJ+oPyE7MBfRlIGL/q8m094IDth9boFmKgLKzZig0zDowt3RPfGjdClm0aC9eVfD614n+vQ+aTBkalpVjVSpMVj0p2ayo1SjPzg4z1sfZzA1kgCLFd3BYQEOpqdbNaoD/oT4R5pBliNH76dv4WGHK4LRwGMQcrYkJYh/Jvbp01yTuehukYvuSFfliqTIqlTyJ65HIzV6zTWFMe4XdiA7ksi5k0ffiadO9yWsS6mthzVSTVGiHEQRxlj9JigJktSpgZLJyYgnRV3ZvD0Z1J9axhtM/sVM494ug68OP0bq9xmF457FVr4z6xQ4=
  template:
    metadata:
      name: ghcr-pull
      namespace: teach
    type: kubernetes.io/dockerconfigjson
