---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teach-secrets
  namespace: teach
spec:
  encryptedData:
    CLAUDE_CODE_OAUTH_TOKEN: AgBUqW9sRYvA1Mti2J2871f1B9yiqOPYGlVxGzCcqsi0irjg6NtodTlUbtT8HMto51owLF60hmV6Lwo1iyoaxctHy+/9w9rktzIz5Fhdqgr328vKyyduVAlTNApBmSm8T9Hqfb5P7kf14uW9KTnnTL//gyGIkBANna8Unl4VioI5Pr7uhKIqaBva7GGHLa4/YMcdJvXXZ2LPthg79YbEmjMOs95ktA7/4iUZsQPBdrP/3Mulpq8vMk8iTEV6L2ACVPeHtP1xvitQufCR0iU6u09lQZfuVqHtqTXArlQ4M63wbe2rBC5EBOce2ENOZSMWpWQkBEE68iZZ0jafpJioA5GseuKcr7g7L9zIkd+I+RLiVopI8JKBRYPy87TNBI3U6eNFUWEp4nk/ZX0RzKDDEtqocdG045U7mwsMFXPKzJwRcLjliatxEXHYhKBlfpIBE5V9XWWgnLjwb5/3DOm8qjucljJXzJ0g9p6bOZN/VNY3C+iq0SXmbTE3iH7jz4lH6oBX4WbDqeRRxhjT628OVez/X2cuSrXb+LeCWt380ljntNXB79nCwAJigERWSRCRxUenNNJy7+Mv29bXnuiJH76I7j+Ik6GSzwUX9w0Qn28wLOLxZPGTSXYH6Uqz/Uh4hQMLheRktg9VZhtC477+wSz2prMs3F/MSBcWmxluom6gTR5did1iG6dsLxCA6DLipywBjOaBVk9ePtBbxsoYF5ScLF55aiWFS0FsY/0oWyjs1e720dQw6p7kv78WtL9tyUrLTCLmlzihX/V2XxFhxGdujK8OjfQ9fWuANdkklkjzbPbGfosodLK46aY6t7MEjiJ575fRbme8RSh29uM=
  template:
    metadata:
      name: teach-secrets
      namespace: teach
