apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rustfs
  namespace: models
secrets:
  - name: rustfs-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: models-secrets
  namespace: models
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: rustfs-secrets
    template:
      metadata:
        annotations:
          serving.kserve.io/s3-endpoint: rustfs-svc.rustfs.svc.cluster.local:9000
          serving.kserve.io/s3-region: us-east-1
          serving.kserve.io/s3-usehttps: "0"
          serving.kserve.io/s3-verifyssl: "0"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: rustfs-secrets, property: access_key }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: rustfs-secrets, property: secret_key }
