apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rustfs
  namespace: models
secrets:
  - name: rustfs-creds
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: track-a-001
  namespace: models
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    serviceAccountName: sa-rustfs
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://mlflow/2/models/m-37685d2d9dc14a9ca80e552c647172d1/artifacts"
