---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-creds
  namespace: models
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDFsaf8EnhtKXy7+J8O+OPNRQONaNXOpG+eWzh8kseGEuJV/9+2NrImfBheMATgF8A32k/ossER5ICXphhwgDnKWRDnqIg0RKKYiMeAIee6aVLgNIAOWmBJjFCmWW24tSBJBjmGG9JUB/g3DsmDib7fIuOczwWibMrKtWvxCvj7wf18MfM6PI1+MpO1eCZQnl/VvqQiA0cCDfe0+VXDy4KzJWfKwCY5FJ/tmi1J1sb9SQ1SF00zvzxgYwAq7iIu8yzyfxH6Zanjo8NfvPG4KwRzayqFKfVL96zY9XxPaIBeYisyikku6BJ1A0GkcIFBsK14HF/JFdeRi4frfVfAG8g1SgjOBP/V6hibh84cw0/AITvcNrAjS7xq1cKs99QQ7deIHv8Q7I3QiZvrP86Qg3LrfBTkkvuJ1aLy9fbP1B9UHTZrK3Q3TaSZ0axEt7gizw02A7jwlHDnDnUfn0eXcYEVvEMamc47y2CHr/nEhlNP7WuV7jPX9kceGfvwK6NB8WLun0GMKhb0dKbkClXwtKV1byHnGXP0YdgKBmoGmqAlkVm2YUA8aFrQk+7ake0c5LV/hMmit7PzP+VpFiaC8axkACiSIUnE1T8nKOzULZeMUxIJFf/b8D+mK3tx5CH6kLNF1Nj9dxdkdahIVl0J7GoJze3MojbJpR+TViivBfRQ2J71f+FONlgyvQy5J8jQ4mcUQBSn7o9fkBck1EJJHm0NiOxfAg==
    AWS_SECRET_ACCESS_KEY: AgA7+Oy9syYN/qmnOCB5Y6jvMm7jnd38JGVR4vIGFU8tlAHMy8javku7W5RIIy2nKCcJOKlvGskHF7V2Nh72M0QstM9Fx+q7irB3Y1x13fXBG/3Ec0lVJ7knQHEB5gKDNN+chgQm9Aib7ygulqOcYyWG3w0J90ycEZ/rOUb6POj4L1WuJ5aoV8rYVZdnBMBXk3nBzW9gkK48hgnlsP1gEQpXFTPKY8hB4FOXpiiBLFE8ssUA8gGHzzTxI7iYdR+vImPUPyVkekAKq+mufa++PqXf7yz5OAhIQtyScnTACkgzFUWHwHAnnG1SNa2QFY4NiaNy0OLxHs7eCh0FDjHKKguk12QJ+Q+MvliTvBBtFdq4zFnGbOLDJWpj9Rslu6jNtoFiE93Ylg+aDmy7KYiWj1HAoxQp8jsGb4uG/0YeU3lnBRWB+weYQNVrOKWXVRq0wQo/e2x2za+ky7NlHkalcTef4G7YyHSUMJz7ipH3gEbbvRtucquM8U42a3GYuGOJyjjaJmEQZr8koCfKWmSf/iP12dRQZ/hu4JmpVn1BR8yFiy7IeM5vXFa9XrfPdgpHJqObJrSuXGUWoue9Omi625Jro1xUFidlIIscKyU3yLnCSSLbRc4RGhhVf3i1UQeZtQH7dz3kEw5Dg1QhguPWqQRPUXNOivb4HFNZ8kFsJ6sFh+cZaKmNAr4gy7XvmTO3mQmkpfq19Lh+R2hiBL8eFUiHv+FAyqPxybwfJT3dYAcCeejSUaTJQOl/
  template:
    metadata:
      annotations:
        serving.kserve.io/s3-endpoint: rustfs-svc.rustfs.svc.cluster.local:9000
        serving.kserve.io/s3-region: us-east-1
        serving.kserve.io/s3-usehttps: "0"
        serving.kserve.io/s3-verifyssl: "0"
      name: rustfs-creds
      namespace: models
