---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCFSEedDXwESid+d85NzSP5kDNj9C9ms3zWENB7bwTL9CWtP5FInKtwpDA7ATzY6Rou91XBqhRCPwdrKEWZtGgop58V1l1KISA1xdG8Hyb2aDeh8iQB6kZ7XwXwfwbCpeTbAJIvVXoKWtLM3VAorBYiguAWd062EHU9dTYae3o+4lyXp7SGhkUxp8le777FDLKoopQnyB72+xB+rX0FYQE6xGYi8fuxMRF362wL2ar16OYo86yT5z3t3Itkiad0PWdYc2DOLqaS9bTbIhRLo4D0HmBNVv8Se6IhogbuRDUN3UmKWLDV0g60VSZ+FSiUvMa0jGYDJtAFTeCvjoseBLyVp/Np4rUrFguIWc3szukl52CHhDNZieRE/Qf7t+z563G1oGTwzuvevF68WwrwpOaZ5LD0JVb7jJDkxW5y+/o2tv2DbGXkm7u7M/N0fD245AlvMKAGDSMQa401vUHkNeMekndEzDTDe3d32uZUsL3Wq/lvwFG2xjOgo5dWYaMTiKXxi0cL3gMY8DMyOpbfLuvjBNN/BLlFAhSHY0NFBVt3mNRtdJyYIuwp3DKAdyjkB+WxIPm7THhr5XYA5KBP1eY0wIseTJNei/z3oCMjdiAJNCyZXQHXdxxFldkSYT1+1fSrwxLcjq37LGTZrrY3UxLd1ISq71J606CCVE5Oeq1D8KDFWRtee0eZmEPHYonGDNXSzaUkgM2ABeSXjAtos0nGVg==
    admin-user: AgCEB8QllYj1cJCQ1AQx0dMPm6kmItXSceZsZk/TPsvfeSnfWfpZ6Zo5METcc7ycV3p5yG9fZPAvJ4+82mkm+XYiR0akqBz/LY4guroHbYtxJQ0IHm05qY/UxoXgRMG9lXM9lCu2nqOhZOASw0B9q/VMNa36VGRH0LYYzwzApkyYKOFcTf91KcS0PBkthAjYlTHS4nxGoeXBI+oRYWQYCm7Zrjl3lwr2vCmsl7kjmFppKInFivNibRyFH/vdE3LjTofkZBbUo7cpmI86o0hjv9bJxzPEUBbXf6/6Y4K469lWOwrypYZbAEdANZQzRgvOH3xWgs1fiWQl2dyy3rTRqapX/x33+tfXo4yuioX4GXtOQYhUyvg+tlfhxgktLOQZ0n9r6EXRirYPJwkDYl2DcYlwP1L9ZJDLYS0G7y2ZR6hM1IpHIKQX98Ir4omD8it+nAxR7nbUOsq9w8mLu39BmTDWdAE8km/k0yYofMYjfeWk3nsLEhiSQyUyKHFvzF5ADdaGQXAUhWRpBrfsum30Xo9ty7mGGrUlTPoME+1HN8oLEH/teAsobBRlAAYS1rAZ5gUh7gMsnXPY7we0DZOeTNMud2lFH+32QZXCLJ5RVXOr8JeKTKEUcEptDUVHCAhc2otsd3VlHgR5LPLTVmlXiVnjkFWsNJd10K0kaJU8GRBtZxgZCdQNYtJRN4oq/BBQIeujn6KwHw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
