---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgANCw1yh1867QkwjdiXhwMMj+z0P+c+sqObvWzuyzX4FCMImjttyUVIAegcUofgpmJOQ56Rcm+mzSMS/v4SJzajPsAXglp/NM53y8LxTuGlGbYCdFvLfZP8Q4AOBvKGA01pSSQzWdNvBvxSTRQuae40LyAXKd4ArblPcZCIugGJ5+ZSRpi9Ngbd7fjrOC3FhLXPAbbX+3LpWBxgrFktCvoRCmtnZUWDM2Xw6Od4ZNKpg4CXv15TcAvpOkzIvpz/iHVNpKDQjIsPm9BbuTeVAjKOo/xEAU0QlBr767kNNRKf+hQXktiTOEhCLuB47VcL6N8JLzpfuabrmKbB21YcGAdgybxJ7zcmqtCxANKOebNqvO+OKrSTJtYQMDDiWtJHE4LsNbB6kwqhWz7Ly6FcjdbasnWU1WdGdJkC7gCdO+n3QupMfUrLpUH3Irs/5gas7hDFwDgV0sLdlHOEFWD3pAfCg7d6VdR562/2PXpuoVNH9dsVpFmWcUyQmpAFG3mZoavjc9CREhyYhdIpLoP1FdOzvFYTmsVaiQplHuNV7aLi/yQ1yjbAAYL2dQx4Umcw0GOkM1cZPTD9b6s6lcLA900RWMpwDVVcvnBM+7kmltP8pQm8QOZccyVB0fHHTxxba/9cMtqYuGVcHydd8mr4B7KXsjwU8iuHsmxEm/vkBLzXB82OGeNExwTEfMUnWvxcI+P11H+WR90dVpaPKN8Vaza4Cg==
    admin-user: AgBYnmrfS1w7PBeCZdqpETP+JSOJsm8qz0Wx5+miLYGsRbBvKupcnC36vKplKMr0/phV8kw8v11ePsrNzVCLaF/L6tjn2JQb71KzVycU57JXCBg47avjQuTDGVum20uUCljQhmOyAf7RyGiVtBw59TS+qzbRL4YiVNG8y22qt67PwLgs4xliTtbGj05/y7NRIQPmpp1dfi9QzeeJimo8474h2qE3Xswf7w5FpWwABMbP7ILgWu4P8GGf6ptVoTQZDUeYvD3wjLLzOGzEXiC1sqBri9NIUFPRgRmZUMCnR/vNoyjCfDK4w5f5OUVgKupfJGcR2w7HJ2LznbrWxBIi0AzHsOt0g1zRtYLDPfpQ+16RitEng5zR0udOVActQOT+hYBjaGcovDXR4JKUWpmW6+eDP16ESwCpdgdDCjNvyRl0cv7hYjDtRR+YgXsdFnahcqZ1ALCxwuQ39iotutpOjuCNPeazgHcj5EPiVaVc3dTapQ3/PMrSdm6OskEhrSc4cck+492fR2mKU4gVHl3+XL+09mVPH/f8ZDwxRsHaMt1uXWT/P+APOYR2Gd+nrapma4BF9AD+Cyd4UPuRIyWpnty2h3aeIKyihBQcBw63WRsU7z2BPb5rUrEbdg7664yONU2nGOoLCKwk12Vp6Ep58+o8ot9fPiDE0JVbBhFJUl7QCyFsnpfDEjQl3GNbIwrTP58j3QknYg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
