---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vllm-secrets
  namespace: vllm
spec:
  encryptedData:
    hf-token: AgBPDufDKpA/DluuK8yOwsaAJGSfWAGiaSWVKzNp001oNAuMsHw6zU9HWryJD07R32Th2+mBX7nnonYNhKHdePAA+QFrg9nucdlLTSwU0+iYTzr7HY34iksgKitu9AxVSA/b2CZMuvL2r6ewq1kT050IOM5IfmLwmt7SKUp3/Kqq/E73Nq4fGDarhu24JgHxt71quIqnydVNCZuWjNFd/Y9RrF9KE+eoK+LkZWW76giVa8/ECegByMi19MNrO6QEUvs98r/BvCzdMXwA2yTWd9qQ83QGwvWA9KsSaxjFB61A7YpOJuGD+8gmkUurUjJbFR0e9EjLSRn6K89hJKNuQK1dTseFLKyT+lK9p0zRmlxUEz+YvCW6m1D0Mx0zuhFGADaY2hO+bV/Q2r0fFaLijm2MBhKxpHB/P4kqpJsrheGBr4oOO2orSo5OzIxCus9o6Dem56CrpBIO7XWCVeEZVitVxwumIUuRkugXc/djTjmf9ncuEojIMpVVMOhgObrZGx8zDftveYvBKyZv9jlbmIzp/dDyQ5QL3eJSqI8S9T5LiT7sEySe17PRmt9MgqNo0pcSLFPXk9iyQcX7Nlm+DhOEd+3GF2qOIofG/lUURAD7jla7FWD6C75Fqr0X6d43n4fWqfwFRvuyjB8o4IPjLYFwKm8j4wMfjcubmPT2FkgxN31dqnMIsK75qws7C69b+C/l1c/6fEhN2OfXVr2LGoYjujqOztDdY59wCvcTrKkxEOmwKWTb
    model: AgAJFYjrhbnhKqjKlTzgNZYBpudcqHXZIMpblSB/iKCQRhiF53bHRxEDSyDpSBWSQCt09TzsDCoMXL4yU9vpoVu5HKikwR8TM9lBHueEeEQaNdJBn0J9n7eCbmJWjJvO7yPxW8dijLr4zZUER11VT+VgIPGJeyTvq9J/p8C+kuNHn06f5F7rebkEin6rmPjIk0ccdscKN6zGEpvuvGZklG0weXvBMXW5VzA+GqboxQk1zx70KJPPdIliji0rOWpSm9oSjHeGsJk11gudociDA1TddNStgyPB9MShlJHQfAQnDMz8HtUIbip96B2a7o5+RffT98Utav2Q9ldT73TBXvTBThs1g25h4tTh+2nCQ0Y6Kf/nTobAY9ggAMgJXs2mgsgFk0/7ZheRS32QZ1KbCecuG8spVQ1/Tqc1O67NvNTvm+xZ7Q7UEM0uvs/rEHPJzr//vuSkuDOkFkMjmIJufX2bpFa30YpqSHdhkWucxb14Cc08jKjpKsD4Gp/HJ+rslDJn6J1tDipEHp/0WKlpSgN/pRdpNanwCN6NRC0lDhE99X33Fe54o+kXxrgqeyHHtz67/5rvtLRKyX8TYeGSjIVoYSWxZLTyKQXRLmFGvrJC8LEG8kcSeftqM1eXXvK8e+VEqFoX4LjT8F/iTUO31bOEkJkNCn/dGmetF8Cg1BxsDQVv/k/M3FCXLkz8GizRBvfeo4i2Sqsywu35N7nhxVL48GSxpLcCMhjb02qSc1VBaA==
  template:
    metadata:
      name: vllm-secrets
      namespace: vllm
