---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vllm-secrets
  namespace: vllm
spec:
  encryptedData:
    hf-token: AgDSlGJJ+xNBxtaCyhBHTxpuXQVpy0I/wbOsBMhg0Lrqnc8XuuneRnrXgAIE+MgGQbwkJgYyTH2oZycjJBPpKAyy2D9sZ+IV1Y+NowYl96Qe1aTzWSNo677110cNHNOcd5tr2Y5KfYLTS2VZbKYUZiwJAwZAmDwevjPwFkuXNS4NHtzTcug7E5tWPlcdPMU1447KyOl0FXQf0Zv+/zvf8RjK/9KNjBrg8VTVUlH04vKvo1532CTciEX18vCSGAu2Cv12ag0cE6JS41J+kchk6No05hAJ0YPQWzQ3QdB9PduWmt1c+PaObS2U/IVC6DLbisA3ywSyfBSQN4QcSaBMqJGUdRWeQVLQ1sGjctISmPK+XAYj2PNZoxGVJufPmkQNyTMn+b27hgNsQWFAbzsKpA7V25+PB0wr+wUwShnIJZyUyNRgYN5FQy2mw0ZcEemUXfFqH/Qw2/Y/E1UbiknleebL6WANRpduGpFh7Ptf2lIW3g0jLBg5a2KC6OdQ8aKBanOukKkm83MJXA3zB8RWkinpGWCpQXODP4egtdINKAP6/z1fvLxnYJpcnKwMAvF513wchX3GxBJ4NP95mMoLQwStGNr59ku3/ZOG89dAvHMfreFbQ3RASL/RB/0O6flrHcNYw8m+rsU75bitT3HdP6C3xhinsVjDpq72o6dBDMgYf4cwbXCtfe4PT6mEixM+E7nYZ/uU/qSwOYj029er5SY3Yd0RDpECiRL6PL0a7aQa3WOeFHAR
  template:
    metadata:
      name: vllm-secrets
      namespace: vllm
