---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vllm-secrets
  namespace: vllm
spec:
  encryptedData:
    hf-token: AgBQtjdcSnjBBIu1EHD2y9R3JblhaaddJuuSQgJ0gJn5+S8hn38boNgO/qnFPOWCbZY0gvQRLOSeGAGvpfieGPm+g8W6OTztDpDu8Faoo2519w3g2cuIc8dTNHUNG+ZTTTnUOrMndeeeYCwq5qgO1v55RBzz+B/5OmnmSbd5bv9zdMZv8d8EdvzvB3BoTp/rNWsiA4tPHcwclIxpBRFO2om4BgY/pXvHS2d3gSDdx+zqzsAJFz3jpdPRyrAirGYsDp338XeK3upvW3zxLIUnEkIBtpSqRQY9hbJw8GrN1K4ubQQf5WqVaQahndfhHCy08x3tqqkvutlZ3WY0TidcMeAn7Ucubt9XYAzWmuzlFnmTqYBmE3GHspCDCVMZkNsWyL/6Sw+TdcKiqpfmMjqfESYtLzPVuuxLz3PCjeWrhZTSfAv/m2M3bI485Bgp0TGZEAblHb1bZpOd6Aq0SZWHfqy5X1Q3tqvllOxjWoqUEuRcuhdxnG562/sYA3UouQoRg+3R7F9Mc4jJ0T0MQ7chmObCPVALjQV2IbwSCRcBMYBvo8vKIGdsZUe6d97tbgU78IfWDfORZvjIu8MiGXIpAWLVNUZBLj7gMXacRAsEnDkbWZME8OBz7nlvC9Yah+hzh/awJchbr24cXOJoHF1lX8PrRvtrhaEWpwEBTlsdvvdiB68ZmEHKVonjYjhmHvvFXE9lF+DwWabNyy0uTDILV/HZneR1EYjjGBqdqIT2ed9ODi2r0yAX
  template:
    metadata:
      name: vllm-secrets
      namespace: vllm
