apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
data:
  configuration.yaml: |
    default_config:

    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
          env:
            - name: TZ
              value: Europe/Stockholm
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-overlay
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1536Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant
        - name: config-overlay
          configMap:
            name: homeassistant-config
---
apiVersion: v1
kind: Service
metadata:
  name: home
spec:
  selector:
    app: homeassistant
  ports:
    - port: 8123
      targetPort: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: home
      port:
        number: 8123
  tls:
    - hosts:
        - home
