apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otbr
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otbr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: otbr
  template:
    metadata:
      labels:
        app: otbr
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: otbr
          image: bnutzer/otbr-tcp:latest
          securityContext:
            privileged: true
            capabilities:
              add: [NET_ADMIN, NET_RAW]
          env:
            - name: RCP_HOST
              value: "192.168.1.219"
            - name: RCP_PORT
              value: "6638"
            - name: OTBR_REST_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: OTBR_REST_LISTEN_PORT
              value: "8081"
          volumeMounts:
            - name: data
              mountPath: /var/lib/thread
            - name: tun
              mountPath: /dev/net/tun
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: otbr
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: otbr
spec:
  selector:
    app: otbr
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
