---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: homeowner
spec:
  encryptedData:
    .dockerconfigjson: AgBjbIEg1OPmWTXzf2RR14+49wWFugKrpRWiuqQwv48gsUPLSbVnASejFp6DKrljtV7/CJ+ebjfABpzc9AIup7fHcV5mLPmDJ+AtKvst7iF82lsc2eG3m+q7rzAqFq7amiSXVWZG1eaWD0XdOZxETRNMn5SW+A2pSsC1timRpj84W/rntxLxx+jXh4iI/Gc4ddUZOAZSpmZuqKgYptg8Pf/OWRIxtZKdBUGO+Up7Kz6nMbuSIBuhA67AK20Hu3cBYwMdyRBu39WTW2h0AiGrhGZFpb46lDXbJVhtxyClkZsslX9L9HVAEE7DIws7EDd4CoN77aQFN1321fGV0EbgH8Q/mRutXTIvUaeQVLeK83i1V8UsvaKSOv6TXWFz24vk3U1N8cPh0rGcqsq2Z0SG/xuGgSLGaMs22KiI67jQL479qq5zJ7gIpUaNPpF4l/NEQyl2sJuj5C3PsS2BIzNT5PHuqnp0Fqiou7BPtklp5OPCpaIbYK4kTAobd+QcwKwi4msBn8HeBYnWbVelFCWE5HFjYYY/Mgr+5oCEGah53PTe54vo4WUGfP0Jfw1WHnjh1T1OS+6tK/60I/3cxOHuJ/8Zgf9gcc/OimvKG8hroqKqHGNYRnA+Fl6NxSSkVix8lgVjhgiGiH0XZFlVysUYV9bqh6fqwypKFoftKZdPYJCm3TtzzqQjotX8VOuaATagWmtBUb0qf5uaLXV8gXPicR3UdOs8ubUEnPjFBEoL372ZqcCVusO52tLWSuPEdzKdQrr0seFqPLGaWcnIu4h72JiCMsiSHUE4xIHULRMsY/xeS+6PSvMbHGVIpkh9pvKiRL3I7zsScINTTJBlFyZX7PBxXjDz4QuT+Z5Xd2/xntsEW6c1zCJq2LnKgEq7/0Ye/WKeqeC81hL4KQa62QjLY7+bLhKphcg4qxrSfg5c/+Ah4RE2+mBPOJR+N+KvV1sdDDQ=
  template:
    metadata:
      name: ghcr-pull
      namespace: homeowner
    type: kubernetes.io/dockerconfigjson
