---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeowner-secrets
  namespace: homeowner
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgB7Zu70nPwyKkopL0two51IvWc1Vl+WGy3SGKNEGRo40GGtBl6kCwpB4XY0Bn8mwyJO0UW9DooJb/AkKuOtnMzio0SkjkW6NggRh1t5I7krBipxI8ED2OMSkSo9LaWm3P9bx9mcBvzTlbNBjJfVjR8Mdr7uA3eFHXxMzznpEAnOB2DftPay/HYDP8R7rSVmXx69MkJnydUwJUE5hmNwTHyKJRx7HScm4oYnpQdes/Jg/YIEDXUfUeN+pqeEkjYJoKm919MSgzyt20PA6Yb4nvxuvukCUU6J1z1Eo7mDVGu4tp2hDHdmTYb5WCISxTIgnnmmtfp7neuMLX0lJSfbr2IqntcQ0OoUNg+GNyANs8NTyl7kEOhOC7PBIhP5QiE6lurGKgfruld1xaa1Etxrsv/6JaXx9RcMQUSpnlcE2pPJIvEBBaZLA5wdjrSs6E4JdIEINuibqs1KoSMDHol82I3qRSWI0bgDIFX9HCyN9qBDDErAlWL6Z8st0ZAvdrCqrLCenxpO1seYDfS8n72Cwra5vSgbfTFGslQnqH31DDITfnBW9DQ7+vHb632uIHHZb/bTao8jCRxGF+KV2E4d8W3tANLUMjDlJ0aM+TX0KWxSsfgsp0pHRNdz7S1c1MvAQITdh7gr9vAna4Piz5zUcQuMx7wTpVD5jQMZx0GstPAoTd6sCiIY8CqNn9VRLSGSFRpR+p0hsIR7fCffo4sPTXcVP3ryrwKXpZJWNMvemcR0gTUaiVWrzgWm5ttiZP/UTzE+FGChfAmaBBzQSFYAv/JZn6iwLTj1/+l7/uH2jlU8fptaGEWboU+ulFfOKmQWocq8+RQrWTr+Nxdo4yk=
  template:
    metadata:
      name: homeowner-secrets
      namespace: homeowner
