apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-external-secrets
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: rustfs-secrets
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: rustfs-secrets, property: access_key }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: rustfs-secrets, property: secret_key }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-external-secrets
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: tailscale-secrets
    template:
      data:
        MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow.{{ .TAILNET }},mlflow.{{ .TAILNET }}:*,127.0.0.1:*,localhost:*"
  data:
    - secretKey: TAILNET
      remoteRef: { key: tailscale-secrets, property: tailnet }
