apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-external-secrets
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: in-cluster
    kind: ClusterSecretStore
  target:
    name: rustfs-creds
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef: { key: rustfs-creds, property: RUSTFS_ACCESS_KEY }
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef: { key: rustfs-creds, property: RUSTFS_SECRET_KEY }
