---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-secrets
  namespace: mlflow
spec:
  encryptedData:
    MLFLOW_SERVER_ALLOWED_HOSTS: AgCYbiGKpNBzwSjKWsAkrcH1/lGygZKo2YQs3He02eGaEnFqKlkz5iwI//O5o1AQjL+BBAukTjURoJhgoi0IvsfzGLh1YidqupsFTbzvHeKApdjTtpSbcSTNCH9pDQ71aSqRd4Yq1nVSBvL5dfmw6tMD5c8ip5bbhVJLtCjdDBNk1yA0Olk5lNZE62WR4uTT2Jvm9IfN03Gy7Maaw3zxQBYJXk2Y7sf8PqCii5DIAi5FrmHNHwkZoAGvGmWPiiet4HZg+weANhM193elPLlogrpddGH3Oe3idtw7i0H0ZHFeTj/RmaTu6R9rJX7oHhubY0lrvO3zNi/tmHm1HWEutmuCwRVzODMzQc1ZVaIPKvlgwvgQYecfuHxa/+Lao30MoaDZBJ9wwfcxTJHrsY7mZhTCv17AXAXPJMvAFdilliwcDetgWyPjtYhLbwxnpSJLP29YSSKTIbxsjMQ6qT+abJ1HI5Mm8ti8l1O2Onq7KQpNTqy1Ggx57Z8LXDg9dravRc4wxYA9JPBEivdWSy9/Z6bbT4iokIEoQ/gLN23jthit3/xWZeHmz2MMoug/UFEvCFIsFMIUrhFh6Lb3Vs200D3KSjzSM3oEtSm/wePtA0FC+cNNnCoGSSL9jZQZ+5OSxj4QDahLoDYAiPt3Z1bwg7Fv1QavepjJN0N3gg/3EsFJTJB4v8JAtmWUVDTX/tcGl2oja/AHEzqbBGpdy32TVn6KqYg6nyBhRNtkN0V9NJvi4Q9fkBj0RVEQGalXq1lnW6JAlbE=
  template:
    metadata:
      name: mlflow-secrets
      namespace: mlflow
