apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mlflow-tracking-server
  template:
    metadata:
      labels:
        app: mlflow-tracking-server
    spec:
      containers:
        - name: mlflow-tracking-server
          image: ghcr.io/mlflow/mlflow #:v3.12.0-full
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install --quiet psycopg2-binary boto3 && \
              exec mlflow server \
                --host=0.0.0.0 \
                --backend-store-uri "$BACKEND_STORE_URI" \
                --default-artifact-root s3://mlflow/
          envFrom:
            - secretRef:
                name: tailscale-secrets
            - secretRef:
                name: rustfs-secrets
          env:
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-db-app
                  key: uri
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://rustfs-svc.rustfs.svc.cluster.local:9000
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-tracking-server
spec:
  selector:
    app: mlflow-tracking-server
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-tracking-server
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: mlflow-tracking-server
      port:
        number: 5000
  tls:
    - hosts:
        - mlflow
