---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-creds
  namespace: mlflow
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgBqx2l+Xmw3vyKRHFZx9FH/mlrJqk7stWLEA68u5KPL+N78HzTm3ldT+uO+ZSogMhP01byzmt7eReYKD6jMSAgHT8a96ExRh+lId35dlOV3ctSswI23EMOS3zD/PdqrTEAyEZv1+tWIiNoztsJ01uHYlrJqEsHEB/4VZLz6ntuzaGnaL7gCYBO1tUoJAk+o/KBd3JMriIReb3yoCCQgyBk2FhwWE7UOXyfSms4FAVQcJcElBCbvy0ypNYqFjfH3esb/e97Ihl/GOgIPSYcVMNkbUWSS00cKtny4saCL05OsvKcos8GYSVts2uyd/qS70l5t3xM6xgvtIt6K5urFvJ+IN4mLa7pUK81uTFLrL/jibHBLTIFlP+tgVSSF8zg47O/nALOoqrV3iC1iMHMo/PSch6NXqXn+/tQ5Nu6tgAPUGGZ+OKuwVsJK4K9A6r4kzX0SjVcXzI/DcAnAdcNhRD/JchtW71ccnbgp0HTdEF+kWo+9PnUegNYkQRkQ2+A2VY/uTuHtQ5dYLxF7U8XJDxMNfbLE67h3KQtGBCy80VO0CJ/Dpiv/l5DARECsZ2Dw7N3d4qHUTm3QR4KdU/oad86FuvLwq7u/lS+rkkIEU7TI5BUZm6llYxGGz1oenFhG+ZqPxs5gzLJF6U0rKOtm4Wzry4q6sX8667wHDUgL/OcenLE5ToIV4YsdhY3kqVMVK0mQ4GGL0tJ6JmM+Js+JlILdEciimQ==
    RUSTFS_SECRET_KEY: AgCka9n7IBqTIpJ7AWSNOKfnP3r3m5cG0wd6IbBqL9rXDiQZymbJv7HDNfddQRbuJYlr+zHdZo3p88GvVhzyL8VCBGD1it1FZwExqdY1TTNPDGV1W1q/GrLc8EDvbn3cALJ0j8hDQD096EKZyf9wS2zKRSdPwrts0EEfOYKcqYWowWNSlFL9h9cT6Ty1nauy1CQHbSWiFvsTnSBQIzKVMDueecCUdOvGKxPnhMe8ZPud8WEcNBmpfxc3OBhZ3YvtjGdhY+aylCNVZt/D1/kAOPfuEBKpxJRyZLVwHz00QvCOhVaZm5clUH6CIn0HSwkYB55YlY8mEbOvifw2pL/mdsFSFUIR8maOJ16Xa0LpzLYd+nktNWGek8fPrPZM1vKKxYpzxKmYi/pqLJNyMaeokApE2heIP8UNpWjpIMrBFlTn1TJ0//c+d0R7DYaGI+EqhyhE+NXacaBcxtCfrtUXTyivHCtZqtJ73KQ6Mx2ZoHzFEcJKFxAwZKPzRUXVqPajiPMnVJE4E/NUcjENmjP4OXskTOFlxR0ekFml5qvxhnYPxAo98h2SNpvyEVRO64l21UH7Iw2z95w56YJz91it4pzjYtyvwXwRgiXdTsNDXMtBbOGMSuc08PlVNx4A5ybfB6N/Zhwz4HA+B6e9e/TiyIHpJStGIB3OXHDidl2uLKeg9JTPNxYJBZrw5iV6gWSfo6IReEDZg/oxmIY8s1xIatBqxDPSNHLKz8kkA8hHvO9F4A0jQz2Ba+Bk
  template:
    metadata:
      name: rustfs-creds
      namespace: mlflow
