---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-creds
  namespace: mlflow
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgDqd4Zz0ZnYbTVbaO4sCiQrVrQCQ+wa/VJMpv6XC02vlRnAUuvUWfejef7b9qW1SRwEEBGCTzr+PKlMXr+f1bOKEw21dEpVLDBjvI+SmtChfkOGM5ydwIo9Z8ZD37PE7Pyl06SFAPvsXpprKUGQpgYQq6fPFKHAZ9gcQR+QKYXMLF5ZQHtBVNG1cKbc+T6RV6A2+OGaf/uZOg0Ni+IAOGIXOYv5DQV9jemzvD2g3OxoDtvGxUun3olTKZONE8x9Qbxl8rOHB578l9WNrW+odbez41J7cc6CGKsxFL+P35IJEOMByRrj+dDLWPINpcJ4Dq6kHs2U/BCKOH2YsTSibYLtptC5rsx+AT1K1Hv2r6Urgyg5liYMQQkmnHbWDaCwl2JDGXs5jy2LHLUqpEvyOa47CrhFWyNZ/2QArMgdB/vfNUiAfRmifllbx4jYLzO9TyyTApSAhSpDMuwwiMpbcCtx0cZ3c+zk9P6zZkP5CuJgzodW25vs0J5kS+UqFbHvSa7qO+1WEHSYfajxlsGuSYp2+EdoN8PsO/2lwr1hPRC+uQ7ucQEyLdaj8vz27pan3GVDseQWF5locKE2W7VT9I0v5aIBpywBHJY7Ze7hRw3vweki935s3hlrZsWmhtS3ql742y6VnZYi7hzrHZgR8thh1lQMDMRGY5yYu2T1joVYePjSurpoNdVIGMe1UlXuakexncL7TUqHJw9kY1UsNnnqEjZe2Q==
    RUSTFS_SECRET_KEY: AgBHE1ipmM898w+/Wxf+oOX+t7yyRmHr14JNiN4BDYyiuxqf5z3eAuZfEFEpExZ80RLrnR+Uk7lojqqDFuSiYGnHLZ1E9SkQ5gcmWJoYdCCyUR/0LcqHPk/FspO3pFl0A84+sv8FjljG4Say2h4tKYbce8ir2LQX+SzRgr4nCBruBz80ZcfJTji9C0MK2itiZs8lmuOFBtxruxLPENHY4RMM4UFMUWzO11k1AVpWmL3/JqzfcERP+YUDHP/9YoWipctSHXckxRyKZW7SoPBBt0Rjv1HoCId6qxkUkFYuQVpOZfjoqaKfMiX3UlD1AOy1KvFjNqusTNK9zIauxlCayqX611+6DNNmYzIsv1j2Sa+gIRfladpnnVRZmO9QxL+EVl5AXtlJharz3HXVFE9EgolQ+pxdb1/2fngZaoE8z5O+dUuidaU32k2JHaiNgw931ZtwZFVNwKyu4cd2zHoh9ymwY6VvrxWiUcSqWMBmr5/0yHotS4oxjRlKE7Lygn+xvkr4xu7Z0+l3NfVB+jBM+ezXXe+NWCm+CVOPyNiagjuFBfFhavZn/9Q7sUyqgB69xOG2/tKAs7v+WdTCU95loRh4QYSe6f96AyP2KjXfJYuBtki8rIQyPUdxC6RoZFWP8ch4cnP77SFLDd8dES/UdCTZdvRnuH8MrsXeqk/nenz8uNgcF85Nm/MXh5Fgelu+fEcbIc77xsB4kxpuc0Q/k9htuSZwT/5pcyxFvT/b8ohIxGvMeoceAyqj
  template:
    metadata:
      name: rustfs-creds
      namespace: mlflow
