---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-secrets
  namespace: shared-secrets
spec:
  encryptedData:
    token: AgAajb+AERZDpC89q+aavu4vRruPAY4VmMQaExb4ZTSFzKHGnOdufaZSXrJDnD1kldjsZ4VfPn7AMZXEtjxwAvLppFGnuFjr3e7KKL52NyQHTxUd75uKpjMC1JFMo4p2mGMRdO/k0ufhM808dIV/kxDobr6msxGK+KUkcBwOaVmG4RKsTyyYATKXXnB8Q8eNfkGO8EfekzHixSWO69zCznrdA30BWfJXaIF+Zk8OOlddVvFMWURa0zcoaZsvk13oJZbIAz/Mke79AJL+U1yot7k4X9cGIlz4ah2u6+elwUq3stEwxRkZ2HvALUHRwh/qhAC6IqMiBplx28ljiKK9XxCJhOqTHsvLiMgcB9WfUokhM8P2cjpM7U9V/7qyMEc+pdy4ZnfflSIJQbGGwl9zV89khQS1flmrNEHY7s1cqWnEcNl+8x5jrzcl8RMEn/QSxPWmQ+FUluLrOmGnHArv+RYlBBdYEpfjsspHWi+Udq//haEKr1hzrcj/lgk9HLlgLuEYBrCxUVICNE5WAIeR/+NBqyqyGRojnz3Nvxp8xOL7CJ0sAryPnZPQuRPsl7SDhWcOKP2ini0Ajj1cCFWlIg6uRk858Vy0nslcr1E93IgpX0GJMz/0QwnKosgH7deIKYSL+GvqQrjqCUlTV33VuVxkzWv8F7B+SB3nodp1VTM1ndzdGjjwkPAZrdEKcSxT3Oi4hPah/3SCoo/2eq2eN7yG8fGxYXIk86p5GMVtMKImvsf6eZCR5uLBDtogg2uQyI1mEQgDYky6t5p5w3OvmO3tIjmJC+txnuq98YbFDrBCHOfXbbNh6+uP3USDBgs=
  template:
    metadata:
      name: github-secrets
      namespace: shared-secrets
