---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secrets
  namespace: shared-secrets
spec:
  encryptedData:
    access_key: AgAK9D5+PjFrWHmTcpReY3/gj1FJZZ9+GM96zTKQNE+piurLhSdGMk5XK8LdT9K1W+lP8UO6q4NTCVux2HSPTIZX307tJtxYNcpLcF6t1hLKKqt1G4R4RqO8VAtoNNaIGVemRHggEZaDHXARbO9D+P4FNBDpzvyaSqZlb5J/ke/f4fbm9KrYzROGilBTVxcgsl+owF1n3w0RQyCIRkb9o+wFdKZULFQErNXxYngoYjI7BkqtMw3XvvzwKwdTV0t9X40CApzkxbf0Dz0hsQnJSqBMByU+YggAFWNXQeAt/U/8xtW6ib78rEVV6CQ01I/Cl1lAaeBXwbdvXD0ZDx92R1Z6neqF+CZRGA7w4ctWWgwlRshZHlD09BuEyJ3yBOyJL/cqufS13L/JHFIXnCaeX6cRZOTLxWUnGjgLnSGFAGO1oRQ/3E0igHdsoyVPuyPiuIsReJQExfaCr7COkVxjFqNfAOmYInZvVzKfRM4iwGnGhnMlz4W9fccJMA38Z6s9xKSTl9x+7SX65qtGWfg94tzwn3lcCyKCv8v/7ESpqE1WLXkRcelw9jeVun26UP9f0T7rE+v8hQBMWsvvp5t1YpEak9PKxrK4bBFURKGccjiOp0CgDOWEZAf0lECMjIW4CWr1+8XjCwOjFiYN9qSmW3iSq3o/aPCF78jSE32mO79fPWDH527xByobSMopmPDQY2Je7utIWAYS27QCIy7M/+WpifhIFg==
    secret_key: AgDFw0vsUx/qvCxohPpxYidDYO1aYAn0zNcYBZYzjOif+Ng1u0PONcXmIgexIBfCmDKFs6G/FhKvwXl1l83k6utxcYvmbOOQB10I32B9BTGy27SLaLnxRQMKejNLHgZpEn/ebR5QYvoLcPIIUVYIcDdxOMRWGw26Sg3CfZY/XC4ljbdV35aTqQ0CCNGL3gT7867O15/ixe3x/gwFghBXQxREqAMzre3uh/9jyUrvDfPFUgM64PhGoAOA5Nmup14gmogi8SCZiDF8B0dUPOtDqvLAeSwNtU57Gnk3gjWxaVS+btjAhzpBAzlS0a2Mjwg9XvtaeXKcYxn9WoKnxuqL1Dt+rAhzqL61erFX9AfkAJMRPstKmMrFHHv7sO2UC0LGaPuq/7XmBEVGdtOedUr8msd1Bpo/ziGiwQ7T9Sg2XY9v1EUVA9QgClZ0ivTAdNKiTXj9h+6LINBdlbODZOopE/e2x72Jc3ru7Mo7RgM1bME2TevxHoRnBPdoCHtca84DSno+E4Z3C5HX1I3l2pFoqFiSM9tWr9GdRSWsQNv4fnDybH2wXL5U3Za4R1PXF8RYFvsY1qlDuEZ7diAxXFjyNOCf2cr07bdXtMFa1r8oMN4+HvNRfZ6YwWYvCs1XppCDvfrBB3c2cLYK0SdfO17iyT1CyZWje4cf53S0tyk1HuBTIAtycJkNG7vw5lUQfugtJjgCkxgBT81X+4tSrvuXSF0t19hX7aU2LMN4fBnrD6lvgMtDMBXJ25M7
  template:
    metadata:
      name: rustfs-secrets
      namespace: shared-secrets
