---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-creds
  namespace: shared-secrets
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgB5kAzqzHkSNX8RtFyPaF25MzLUdV8zG91FGqACKLj6evboB3jCes4+KAVbY8fSve7X8i9WFExN82VlneggObahTdAv1QfeBp4VXr10+rZM6HVEW5QwaxqTH0tJp47ZYQYpcOiB43hgQGNwfl3ChjCtsZ6Oku5IQpHjlWOjGKZJdzfxE/+D/R+7r7pn5Tx0l7f2WbqsHpk0HF1IJSFWzM+rSrNXXUEGdcLoyqqcUuR+uUsEIP0AO1BjFpugZhTk47kvXBmUDIEbxeVdnNOhQL06Yaa2S+QZXeQW83FfIWNgUd3BCokrkk3QDx1zhiqKkeDcL41El0KxFw20a6rwTVMWHJpZ0EnUcnDoKA+CuZntvTAzKhuccRMFi3hlV+AVCEKRR6lsc7IjPRvXrxWs9z861W9q2ELpz5zNKMfluXbnohAOd07iiAanTG51JIyuW4+I01LEMnbOqt3DVO8ZB5i3Hzl23CoWQGzhSEPJcIpTt3D/02tv0oLbtoEm//5+nmFXZDtp5Ei7aR/dJIJy7CknLZOt+VK/SIvX0u1Gro4Cddo06xmqldVpAKFvfvarQRg042XiTup3p632awxjjz2UoVjA07kjknkOfENs3gJgmTRT8L3L6yjqcwsfyHGc12IOIoYWAUe1baxUy/AGkkXT6oGXCP5uorWSkRVsV/G6ZGVszNYSns16ntQf9kT6wBamSQAWMC22ZK5zjSJzORk9niFaIQ==
    RUSTFS_SECRET_KEY: AgCzjQwXNS8qyL0pQZwrDQV6mr5kuYi21Tz1MnN9yc3jikd5ETd4bimjeg/PM4qidMAyeRVJGhAmCMciwC3LQoo+EASkTinYHrYBa9YK05aTs/ij+DKl1F4nHCfBa6AXcl43nYlYkT0yZHv/tDToI6cQiQfJnj0QcYHx32DPoomSAWLhDLUqAPBVdVSBcUXsZBKDnfw9T6GIoNsbRR601fZtgNnd6dYGn5YuYvufDuNAunpE2LR51RpxjAu6O2n2Eh6230dZ+0392ADiV+ige83Xvqt0qlAcoQKToGi+5HJdVJVq8cANTzilzMH9RU+xuwFAB+CFryW9iMx2G03Y+TObdGc1z4do78KdDTuF1lD9CmTpvc0sVP9y4qdHIm/2gRa7DJIXO+qoguHq/v/AyuFOqCv7ECyOWQyZaNoJJ+muE5EzkmUnDOjX30eOUM3JZhPJeEIKoHKnrw8rAAUH9ge3hp0fbOwXoMD7tUn1u54TaPwgpET2MwXQCcK6H21YTMaHA5VV/Qfl57pQFXBFOThj6Xj1bLxUsLMfthG5z+f6w4XyZxgJF89q2FBYL6SEzg2/mJsXRjjPXqfLQiAssZ40TDAg+Tp6051QO+L7KAQfb2i4Hqujmp1M5cguIueEQns4mkufE8K8IGJNBhef0NOKATG2rp6r0tIeLMzewuST5I2s41IKkL+c6F4YQGQgGUyTx3ySM5Jh9BUdNtN0G6xHUuSJtV08RDZoWl5NISxVTF7QlKTC2pjt
  template:
    metadata:
      name: rustfs-creds
      namespace: shared-secrets
