---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-secrets
  namespace: shared-secrets
spec:
  encryptedData:
    tailnet: AgBCVS3eekK2cC/r3YEimU6hDtrdxA+3warDRVVReuzORHTHYCojrhW8aN8h2trkAVH7MHFaYncDiOTqfgX+Immn4TAhwwYXmbCC6us6a03fHdXtah+HxetKKezy7Qxl/oI8mS3RPmHq7P4ZtD7nACcq2CRbXA49maCDzCWQS3jYHOqGBCeaNbV3oSNiSMANTQlx81IbtGIa3rqKbCzVDmFWJ/eoThvtIQWeNBaG638qsZnPws+aT7IdRxxoVWmeQ60YtSfRs/PzwPW7xPLrAl1L5mFj8xZgtd66UonWWHnn/HYNruKZjF/UU6ncxd4zlwt5+ij7gZw0//MlSewN+MnmBW/BlHxvO7Tb7e894nZICgkgDEPb96qheFvldXLKKHQQV6Y7aLpJIoz8qexps8dsDIN2+6nrcOOnDGYE3DZ77CXvj2z0HdDIOOlYBrYrSBf+tkhRfYNjgCqhqRS+my/Snq1AQcwI8O7+z4DAxbLt8jgiUlLVSUZaZ4yRvc2lmcmO2bgplMZnHm4SgsRtXtCywpkrkJeE/z57yYA1jk5D37xkn5B256rTnrrnhpNMIkq1sZFWWPCmke4qjZePl4pvIDq060MnSE+LBm3d6OaUeYoVbSyXldL807I6MAdBQy27u7gTCiE0tFQE6MJCvL22pAdu1IzHA+O+M4d8sX9CykKXjLNvpWP4J7PLv1YRnFGETNFmBOq0AEcQz2xpafJVFg==
  template:
    metadata:
      name: tailscale-secrets
      namespace: shared-secrets
