apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve-crds
    targetRevision: v.0.17.0-rc0
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve
    targetRevision: v.0.17.0-rc0
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
