apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rustfs.com
    chart: rustfs
    targetRevision: 0.2.0
    helm:
      releaseName: rustfs
      values: |
        mode:
          standalone:
            enabled: true
          distributed:
            enabled: false
        replicaCount: 1
        secret:
          existingSecret: rustfs-creds
        ingress:
          enabled: false
        storageclass:
          name: local-path
          dataStorageSize: 10Gi
          logStorageSize: 1Gi
        affinity:
          podAntiAffinity:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antonlundstroem/homelab.git
    path: gitops/manifests/rustfs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
