apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/antonlundstroem/homelab.git
    path: gitops/manifests/shared-secrets
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
